services:
  - type: web
    name: mu-injection-manager
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MU_ADMIN_USERNAME
        sync: false
      - key: MU_ADMIN_PASSWORD
        sync: false
